import React from 'react';
import './Conciousness.css';
import Comments from '../components/Comments';


function Conciousness() {
    
    return (
      <div className="Conciousness">
        <h2>Garrick's Thoughts on Artificially Intelligent Conciousness</h2>
        <p>I think that conciousness is beyond technological innovations. The question
          of whether or not we can create machines that are truly concious is to me the wrong question. Machines
          can be self aware, but I am not sure that, that would be the same thing as being concious. Essentially, there is wakefulness,
          then there is the dream state, then there is black dream state, and after that is full conciousness. In order to get
          to the concious state you have to do yoga, a special drug, or die then you'll reach self-realzation, or moksha.</p>
          <p>In The Correspondence, Princess Elizabeth of Bohemia presents Rene Descartes with questions that highlight a problem with Cartesian dualism. If physical matter is only moved by other physical matter, and a soul is an immaterial thing with no extension, how does the soul move the body? Descartes attempts to address Elizabeth’s challenge. In what follows, I will argue that Elizabeth’s challenge is successful because Descartes does not adequately defend his theory of dualism. Additionally, I will suggest that if the soul and body are connected then they are either totally matter, totally mind, or connected by a third substance, spirit, which is beyond both matter and mind.</p>
          <p>To understand Descartes' idea of dualism we must first understand the terminology he uses. In Meditations on First Philosophy, Descartes separates the world into two distinct substances, mind and matter. A substance is something which can exist on its own. Matter is characterized as anything that has extension, res extensa (Descartes, 1993). Extension means the substance exists in physical space, can be measured, and adheres to the laws of physics (Sturm, 2021). Mind, on the other hand, is a purely mental substance, defined by the ability to think, sense, and feel, known as res cogitans (Descartes, 1993). Mind, unlike matter, has no extension.</p>
          <p>Descartes’s argument for dualism goes like this. In order for something to be considered dualism, there must be a clear separation between two things, for example good and evil (Robinson, 2020). Descartes is focused on the separation of mind and body. His first premise is that it is imaginable  that one’s mind might exist without one’s body (Robinson, 2020). This means that a person can imagine not having a body. For example, a person can doubt that their hands exist, but they cannot doubt the thought they are having (Sturm, 2021). With this, Descartes believed that the mind was essential to his nature, and a person could not exist without mind. Since it was possible that one’s mind might exist without one’s body, Descartes concluded that the mind was a separate entity from the body (Robinson, 2020). Thus, establishing his idea of Cartesian dualism. In the letters to Princess Elizabeth, Descartes mainly talks about the soul. The soul, according to Descartes, is a unified mental substance, that which makes a person a person, and is conceivable with our understanding only (Sturm, 2021).</p>
          <p>Elizabeth’s challenge comes to fruition because of this idea of a soul that is mental in nature only. Elizabeth first asks Descartes “how the soul of a human being can determine the bodily spirits, in order to bring about voluntary actions (Descartes, 2007),” meaning how can a soul move the body? All matter that is moved, moves due to a collision, a push or pull, or by the shape of the surface it is on. For example, a ball rolling down a ramp. All of these scenarios require extension, or physical contact. If the soul is a totally immaterial thing, part of the mind, and has no extension, then how could it bring about movement in the body, which is a material thing, made of matter. </p>
          <p>Descartes answers that since the soul is united to the body, it can act on and be acted upon by it. He then goes on to explain that the soul and body are united, and the ability of the soul to move the body depends on this union. He doesn’t say exactly how they are united, but he does say that we cannot appeal to the way one body is moved by another, in order to conceive the way in which the soul moves the body (Descartes, 2007). Essentially, the soul moves the body in a different way than two physical things move each other. The soul uses some type of power, or force, that he will later explain in Physics, and he uses heaviness, or what we now call gravity, as an example of something immaterial that moves our bodies which are material. </p>
          <p> Elizabeth is still not satisfied with this answer as she presses Descartes' example of gravity. She says his example doesn’t make sense and it would be easier for her to believe that the soul does have extension, than for her to believe that an immaterial thing can move a material thing (Descartes, 2007). Descartes’ replies that Elizabeth is thinking too much and she should relax more. In order to understand things which pertain to the union of the soul and the body, one must use their senses, because they are known only obscurely by the understanding alone, or even by understanding aided by imagination (Descartes, 2007). He is telling her that she needs to meditate, or stop thinking, and become one with her senses in order to clearly understand this complex issue. He says if she stops philosophizing, and only uses her senses, she will be able to conceive of the union between body and soul as one single thing(Descartes, 2007). He also tells her to feel free to believe that the soul has extension because when doing so it is basically thinking of the soul and body as one (Descartes, 2007). Elizabeth replies that she still doesn’t understand, but thanks Descartes for his effort.  </p>
          <p>I believe that Elizabeth’s challenge to dualism does succeed. For the nonphysical soul to move the physical body there must be a connection. When two things are connected they become one. One thing cannot be made of two substances. If the soul and body are connected then they are either totally matter, totally mind, or connected by a third substance, spirit, which is beyond both matter and mind. I believe that only things of the same substance can interact, therefore I created a third all encompassing substance to account for the interaction between soul and body. </p>
          <p>Cartesian dualism draws the distinction between the mind and body, however the notion that the mind and body are united is not something that is often discussed. Descartes admits that the soul and body are one when they are united, and that the power that causes movement in the body is because of the union between soul and body. If something is to be considered dualism, there must be a distinction between two things. If it is true that the soul and body become one when united, then I believe that it is no longer dualism. </p>
          <p>For Elizabeth, this idea would be similar to physical substance monism since it is difficult for her to understand the interaction between physical and nonphysical. For Descartes, I consider him to be more of an early idealist than a pure dualist, since he believes that who he is comes from his soul, which is more a part of his mind than his body. Finally, for me I would consider myself a spirit substance monist, where spirit is defined as everything that there is in the universe and beyond. That substance of which God is made of, and God is. Most closely related to the idea of Para Brahman from Advaita Vedanta.</p>
          <p>Finally, Elizabeth’s challenge to dualism succeeds because she forces Descartes to reveal that dualism as he describes is not completely dual. There is a point in dualism where the two substances merge into one and interact, and this is where it becomes not dualism anymore. I argue that there is a third substance that combines all of thoughts and things into one, and this provides an explanation for how the soul and body could be able to interact. I am certain that Descartes already realized this which is why he tells Elizabeth it is very necessary to have understood well once in one’s life the principles of metaphysics, since it is these that give us knowledge of God and of our soul (Descartes, 2007).</p>
        
        <h3>Leave YOUR Thoughts Down Below</h3>
        <Comments></Comments>
      </div>
    );
}

export default Conciousness;